networks:
  pankb-net:
    name: pankb-net
    external: false

services:
  mongodb:
    container_name: pankb-mongodb
    image: mongo:8.0.3
    restart: always
    command: [ '--auth', '--wiredTigerCacheSizeGB=1' ]
    volumes:
      - ./docker-entrypoint-initdb.d/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - /data/mongodb:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - pankb-net