COUNTRIES = {
    "Afghanistan": "Afghanistan",
    "Aland Islands": "Aland Islands",
    "Albania": "Albania",
    "Algeria": "Algeria",
    "American Samoa": "American Samoa",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Anguilla": "Anguilla",
    "Antarctica": "Antarctica",
    "Antigua and Barbuda": ["Antigua and Barbuda", "Antigua", "Barbuda"],
    "Arctic": "Arctic",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Aruba": "Aruba",
    "Atlantic": "Atlantic",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaijan",
    "Bahamas": "Bahamas",
    "Bahrain": "Bahrain",
    "Baltic": "Baltic",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarus": "Belarus",
    "Belgium": "Belgium",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bermuda": "Bermuda",
    "Bhutan": "Bhutan",
    "Bolivia": "Bolivia",
    "Bonaire, Sint Eustatius and Saba": ["Bonaire, Sint Eustatius and Saba", "Bonaire", "Sint Eustatius", "Saba"],
    "Bosnia and Herzegovina": ["Bosnia and Herzegovina", "Bosnia", "Herzegovina"],
    "Botswana": "Botswana",
    "Bouvet Island": "Bouvet Island",
    "Brazil": "Brazil",
    "British Indian Ocean Territory": "British Indian Ocean Territory",
    "Brunei Darussalam": "Brunei Darussalam",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cambodia": "Cambodia",
    "Cameroon": "Cameroon",
    "Canada": "Canada",
    "Cape Verde": "Cape Verde",
    "Cayman Islands": "Cayman Islands",
    "Central African Republic": "Central African Republic",
    "Chad": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Christmas Island": "Christmas Island",
    "Cocos Islands": "Cocos Islands",
    "Colombia": "Colombia",
    "Comoros": "Comoros",
    "Congo": "Congo",
    "Congo, The Democratic Republic of the": ["Congo, The Democratic Republic of the", "DR Congo", "DRC"],
    "Cook Islands": "Cook Islands",
    "Costa Rica": "Costa Rica",
    "Cote d'Ivoire": "Cote d'Ivoire",
    "Croatia": "Croatia",
    "Cuba": "Cuba",
    "Cura\u00e7ao": "Cura\u00e7ao",
    "Cyprus": "Cyprus",
    "Czech Republic": ["Czech Republic", "Czechia"],
    "Czechoslovakia": "Czechoslovakia",
    "C\u00f4te d'Ivoire": "C\u00f4te d'Ivoire",
    "Denmark": "Denmark",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Dominican Republic": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Egypt": "Egypt",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Equatorial Guinea",
    "Eritrea": "Eritrea",
    "Estonia": "Estonia",
    "Ethiopia": "Ethiopia",
    "Falkland Islands": ["Falkland Islands", "Malvinas"],
    "Faroe Islands": "Faroe Islands",
    "Fiji": "Fiji",
    "Finland": "Finland",
    "France": "France",
    "French Guiana": "French Guiana",
    "French Polynesia": "French Polynesia",
    "French Southern Territories": "French Southern Territories",
    "Gabon": "Gabon",
    "Gambia": "Gambia",
    "Georgia": "Georgia",
    "Germany": "Germany",
    "Ghana": "Ghana",
    "Gibraltar": "Gibraltar",
    "Greece": "Greece",
    "Greenland": "Greenland",
    "Grenada": "Grenada",
    "Guadeloupe": "Guadeloupe",
    "Guam": "Guam",
    "Guatemala": "Guatemala",
    "Guernsey": "Guernsey",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haiti": "Haiti",
    "Heard Island and McDonald Islands": ["Heard Island and McDonald Islands", "Heard Island", "McDonald Island"],
    "Holy See": ["Holy See", "Vatican City State"],
    "Honduras": "Honduras",
    "Hong Kong": "Hong Kong",
    "Hungary": "Hungary",
    "Iceland": "Iceland",
    "India": "India",
    "Indian": "Indian",
    "Indonesia": "Indonesia",
    "Iran": "Iran",
    "Iraq": "Iraq",
    "Ireland": "Ireland",
    "Isle of Man": "Isle of Man",
    "Israel": "Israel",
    "Italy": "Italy",
    "Jamaica": "Jamaica",
    "Japan": "Japan",
    "Jersey": "Jersey",
    "Jordan": "Jordan",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Kiribati": ["Kiribati", "Line Islands", "Palmyra Atoll"],
    "Korea": ["Korea", "Korea, Democratic People's Republic of", "Korea, Republic of", "South Korea"],
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Kyrgyzstan",
    "Laos": "Laos",
    "Latvia": "Latvia",
    "Lebanon": "Lebanon",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Libya": "Libya",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Macao": "Macao",
    "Macedonia": "Macedonia",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Malaysia": "Malaysia",
    "Maldives": "Maldives",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marshall Islands": "Marshall Islands",
    "Martinique": "Martinique",
    "Mauritania": "Mauritania",
    "Mauritius": "Mauritius",
    "Mayotte": "Mayotte",
    "Mediterranean": "Mediterranean",
    "Mexico": ["Mexico","Mexica"],
    "Micronesia": "Micronesia",
    "Moldova": "Moldova",
    "Monaco": "Monaco",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Montserrat": "Montserrat",
    "Morocco": "Morocco",
    "Mozambique": "Mozambique",
    "Myanmar": ["Myanmar", "Burma"],
    "Namibia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Netherlands": "Netherlands",
    "New Caledonia": "New Caledonia",
    "New Zealand": "New Zealand",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "Niue": "Niue",
    "Norfolk Island": "Norfolk Island",
    "Northern Mariana Islands": "Northern Mariana Islands",
    "North Sea": "North Sea",
    "Norway": "Norway",
    "Oman": "Oman",
    "Pacific": "Pacific",
    "Pakistan": "Pakistan",
    "Palau": "Palau",
    "Palestinian Territory": ["Palestinian Territory", "Palestine"],
    "Panama": "Panama",
    "Papua New Guinea": "Papua New Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Pitcairn": "Pitcairn",
    "Poland": "Poland",
    "Portugal": "Portugal",
    "Puerto Rico": "Puerto Rico",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russia": ["Russia", "Russian Federation"],
    "Rwanda": "Rwanda",
    "R\u00e9union": ["R\u00e9union", "Reunion"],
    "Saint Barth\u00e9lemy": "Saint Barth\u00e9lemy",
    "Saint Helena, Ascension and Tristan da Cunha": ["Saint Helena, Ascension and Tristan da Cunha", "Saint Helena", "Ascension", "Tristan da Cunha"],
    "Saint Kitts and Nevis": "Saint Kitts and Nevis",
    "Saint Lucia": "Saint Lucia",
    "Saint Martin": "Saint Martin",
    "Saint Pierre and Miquelon": ["Saint Pierre and Miquelon", "Saint Pierre", "Miquelon"],
    "Saint Vincent and the Grenadines": ["Saint Vincent and the Grenadines", "Saint Vincent", "Grenadines"],
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": ["Sao Tome and Principe", "Sao Tome", "Principe"],
    "Saudi Arabia": "Saudi Arabia",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Seychelles": "Seychelles",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapore",
    "Sint Maarten": "Sint Maarten",
    "Slovakia": "Slovakia",
    "Slovenia": "Slovenia",
    "Solomon Islands": "Solomon Islands",
    "Somalia": "Somalia",
    "South Africa": "South Africa",
    "South Georgia and the South Sandwich Islands": ["South Georgia and the South Sandwich Islands", "South Georgia", "South Sandwich Island"],
    "South Korea": "South Korea",
    "Spain": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudan",
    "Suriname": "Suriname",
    "Svalbard": "Svalbard",
    "Swaziland": "Swaziland",
    "Sweden": "Sweden",
    "Switzerland": "Switzerland",
    "Syria": ["Syria", "Syrian Arab Republic"],
    "Taiwan": "Taiwan",
    "Tajikistan": "Tajikistan",
    "Tanzania": "Tanzania",
    "Thailand": "Thailand",
    "Timor-Leste": "Timor-Leste",
    "Togo": "Togo",
    "Tokelau": "Tokelau",
    "Tonga": "Tonga",
    "Trinidad and Tobago": ["Trinidad and Tobago", "Trinidad", "Tobago"],
    "Tunisia": "Tunisia",
    "Turkey": "Turkey",
    "Turkmenistan": "Turkmenistan",
    "Turks and Caicos Islands": ["Turks and Caicos Islands", "Turks", "Caicos"],
    "Tuvalu": "Tuvalu",
    "USA": ["USA", "United States","United States of America", "US"],
    "USSR": "USSR",
    "Uganda": "Uganda",
    "Ukraine": "Ukraine",
    "United Arab Emirates": ["United Arab Emirates", "UAE"],
    "United Kingdom": ["United Kingdom", "UK"],
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Venezuela": "Venezuela",
    "Viet Nam": ["Viet Nam", "Vietnam"],
    "Virgin Islands, British": "Virgin Islands, British",
    "Virgin Islands, U.S.": ["Virgin Islands, U.S.", "virgin Islands"],
    "Wallis and Futuna": ["Wallis and Futuna", "Wallis", "Futuna"],
    "Yemen": "Yemen",
    "Yugoslavia": "Yugoslavia",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe",
    "?": ["missing", "not applicable", "not determined", "nan", "null", "unknown", "NA", "restricted access", "N/A", "none", "not available", "not provided", "not collected", "none", "-", "misssing"]
}